apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-worker
  namespace: temporal-vault-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-worker
  namespace: temporal-vault-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-worker
  template:
    metadata:
      labels:
        app: order-worker
    spec:
      serviceAccountName: order-worker
      enableServiceLinks: false
      containers:
        - name: order-worker
          image: temporal-vault-order-worker:local
          imagePullPolicy: IfNotPresent
          env:
            - name: TEMPORAL_ADDRESS
              value: temporal:7233
            - name: TEMPORAL_NAMESPACE
              value: default
            - name: ORDERS_TASK_QUEUE
              value: orders-tq
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: temporal
            - name: POSTGRES_USER
              value: temporal
            - name: POSTGRES_PASSWORD
              value: temporal
            - name: USE_VAULT_DB_CREDS
              value: "true"
            - name: VAULT_ADDR
              value: http://vault:8200
            - name: VAULT_AUTH_METHOD
              value: kubernetes
            - name: VAULT_KUBERNETES_ROLE
              value: order-worker
            - name: VAULT_DB_MOUNT
              value: database
            - name: VAULT_DB_ROLE
              value: order-worker
